- Web App Frontend/package.json
- Web App Frontend/src/Pages/App/App.js
- Web App Frontend/src/Pages/UserForm/UserForm.css
- Web App Frontend/src/Pages/UserForm/UserForm.js
- Web App Frontend/src/Pages/UserForm/UserForm.test.js
- backend/models/Users.js
- backend/package.json
- backend/routes/Users.js
Inscription des utilisateur + les test unitaires qui vont avec
> Ajout de l'inscription utilisateur

- Web App Frontend/src/Components/AnimalCard/AnimalCard.css
- Web App Frontend/src/Components/AnimalCard/AnimalCard.js
- Web App Frontend/src/Components/AnimalCard/AnimalCard.test.js
- backend/models/Annonces.js
- backend/routes/Annonces.js
close US#60
Ajout du type d'activité dans le model Annonces
Modification de la route /Annonces pour envoyé le type d'activité 
Modification du composant AnimalCard pour afficher le type d'activité sur la carte
Ajout des tests pour tester le type d'activité envoyé en props au composant animalCard
> US#60 Affichage du type d'activité sur une annonce

- Web App Frontend/src/Components/FormPet/FormPet.css
- Web App Frontend/src/Components/FormPet/FormPet.js
- Web App Frontend/src/Components/FormPet/FormPet.test.js
- Web App Frontend/src/Pages/CreatePet/CreatePet.css
- Web App Frontend/src/Pages/CreatePet/CreatePet.js
- Web App Frontend/src/Pages/CreatePet/CreatePet.test.js
- backend/.gitignore
- backend/middleware/Error.js
- backend/middleware/ImagesMiddleware.js
- backend/middleware/verifyToken.js
- backend/routes/Users.js
> Just chialing

- Web App Frontend/src/Pages/Account/Account.css
- Web App Frontend/src/Pages/Account/Account.js
- Web App Frontend/src/Pages/Account/Account.test.js
- backend/routes/Users.js
Une page pour le profil qui va chercher les infos dans la DB pour les afficher
> US #15 Page d'affichage du profil

- Web App Frontend/src/Pages/Home/Home.js
Révision du texte de la page accueil pour mieux s'adapter aux objectifs du projet
> ajout texte HomePage 

- Web App Frontend/src/Components/CustomNavbar/CustomNavbar.css
- Web App Frontend/src/Components/CustomNavbar/CustomNavbar.js
- Web App Frontend/src/Pages/Annonces/Annonces.js
- Web App Frontend/src/Pages/Error/Error.js
- Web App Frontend/src/Pages/Home/Home.js
- Web App Frontend/src/Pages/Login/Login.js
- Web App Frontend/src/Pages/MesAnnonces/MesAnnonces.js
- Web App Frontend/src/Pages/NewAnnonce/NewAnnonce.js
- Web App Frontend/src/Pages/Propositions/Propositions.js
- Web App Frontend/src/Pages/Register/Register.js
> us #37 implémentation de la barre de navigation

- Web App Frontend/src/Components/UserCard/UserCard.test.js
- Web App Frontend/src/Pages/Annonces/Annonces.js
- Web App Frontend/src/Pages/Annonces/Annonces.test.js
closes #85 
Ajouts de tests pour la page Annonces
Fix des tests de UserCard qui plantait
> Tests Intégration <Annonces> + fix <UserCard>

- Web App Frontend/src/Components/AnimalCard/AnimalCard.css
- Web App Frontend/src/Components/AnimalCard/AnimalCard.js
- Web App Frontend/src/Components/AnimalCard/AnimalCard.test.js
- backend/routes/Annonces.js
Ajout de l'information si un animal est stérile ou non dans les cartes des annonces
création du css pour stylisé les checkbox (vert ou rouge) si elles sont coché ou non 
fixe du bug de la page /mesannonces suite a une précédente pull request
> US#63 + fixe /mesannonces

- Web App Frontend/src/Pages/Home/Home.css
- Web App Frontend/src/Pages/Home/Home.js
Changement des photos de place
Retournement d'une photo
Reajustement du style des images
> Technical Task #98

- .github/workflows/test.yml
Ajout des tests automatiques lors d'un push ou d'un pull request sur la branche "dev"
> Test Automation

- .gitignore
- Web App Frontend/src/Pages/Login/Login.css
- Web App Frontend/src/Pages/Login/Login.js
Fix du login en remplaçant data par body et en traitant correctement les érreurs
> Fix du login

- .github/workflows/test-backend.yml
- .github/workflows/test-frontend.yml
- backend/config/config.json
- backend/index.js
- backend/package.json
- backend/routes/Annonces.js
- backend/test/Annonces.test.js
- backend/test/Pets.test.js
- backend/test/Propositions.test.js
- backend/test/Users.test.js
Ajout des tests automatiques pour le backend.
Automatisation grâce au fichier test-backend.yml qui reprend la même template que le fichier test-frontend.yml dans le dossier .github/workflows.
> Backend Automation Testing

- .github/workflows/test-backend.yml
- backend/config/config.json
Réparation des tests du Backend en localhost
=> voir message de commit
Vous pouvez maintenant lancer vos tests avec npm test , dans le backend.
> Backend Testing Fix

- .github/workflows/test-backend.yml
- .github/workflows/test-frontend.yml
Modification des fichiers de lancement des tests pour correspondre à notre nouvelle structure de branchs
> Automation Test Fix

- Web App Frontend/src/Pages/MesAnnonces/MesAnnonces.js
- Web App Frontend/src/Pages/NewAnnonce/NewAnnonce.js
- Web App Frontend/src/Pages/Propositions/Propositions.js
Fix des warnings dans la console de node.
Les warnings bloquait la mise en production continu car le build s'arrête s'il détecte des warnings.
> Fix Warning Errors (Eslint)

- README.md
Ajout du Readme pour mieux informer les visiteurs de notre repo sur le projet et les étapes d'installation  
Cliquez ici pour voir le Markdown directement :
> Redaction du Readme

- backend/package.json
Modification du npm start pour démarrer correctement le serveur nodejs
> Fix Npm Start

- Web App Frontend/src/Pages/Account/Account.js
- Web App Frontend/src/Pages/Annonces/Annonces.js
- Web App Frontend/src/Pages/CreatePet/CreatePet.js
- Web App Frontend/src/Pages/DetailAnnonce/DetailAnnonce.js
- Web App Frontend/src/Pages/Home/Home.js
- Web App Frontend/src/Pages/Login/Login.js
- Web App Frontend/src/Pages/MesAnnonces/MesAnnonces.js
- Web App Frontend/src/Pages/NewAnnonce/NewAnnonce.js
- Web App Frontend/src/Pages/Propositions/Propositions.js
- Web App Frontend/src/Pages/Register/Register.js
- Web App Frontend/src/config.json
Création d'un fichier json contenant le lien vers l'api externe à modifier dans le cas de la mise en production.
> Création API_URL

- Web App Frontend/src/Components/AnimalCard/AnimalCard.js
- Web App Frontend/src/Components/AnimalCard/AnimalCard.test.js
- Web App Frontend/src/Components/ReturnButton/ReturnButton.js
- Web App Frontend/src/Components/ReturnButton/ReturnButton.test.js
- Web App Frontend/src/Pages/DetailAnnonce/DetailAnnonce.js
Ajout de tests pour les composants AnimalCard et ReturnButton
'npm test' pour tester
Réparation de la page detailAnnonces qui ne fonctionnait pas 
⚠️ Faut faire de meilleurs reviews
> Testing AnimalCard et ReturnButton

- Web App Frontend/src/Components/CustomNavbar/CustomNavbar.js
- Web App Frontend/src/Pages/App/App.js
- Web App Frontend/src/Pages/Home/Home.js
Déchainez-vous, j'ai caché quelques fautes dans cette pull request
Bonne chance 
à vos reviews 👍
> TT#143 et TT#132

- Web App Frontend/src/Pages/CreatePet/CreatePet.js
- backend/models/Pets.js
- backend/routes/Annonces.js
- backend/routes/Pets.js
- backend/test/Annonces.test.js
Je reprends la même méthode que pour le user et l'applique à l'animal. J'ai aussi refix le form
> Ajout d'une photo à la création d'un animal

- Web App Frontend/src/Components/AnimalCard/AnimalCard.css
- Web App Frontend/src/Components/PrivacyPolicy/PrivacyPolicy.css
- Web App Frontend/src/Components/PrivacyPolicy/PrivacyPolicy.js
- Web App Frontend/src/Components/PrivacyPolicy/PrivacyPolicy.test.js
- Web App Frontend/src/Pages/Register/Register.css
- Web App Frontend/src/Pages/Register/Register.js
Je un-revert le revert qui a sauvé les tests automatique
PS : plus jamais ça
> Affichage de la Privacy Policy

- Web App Frontend/src/Components/CustomNavbar/CustomNavbar.js
- Web App Frontend/src/Pages/Account/Account.css
- Web App Frontend/src/Pages/Account/Account.js
- Web App Frontend/src/Pages/Annonces/Annonces.js
- Web App Frontend/src/Pages/CreatePet/CreatePet.js
- Web App Frontend/src/Pages/DetailAnnonce/DetailAnnonce.js
- Web App Frontend/src/Pages/Error/Error.js
- Web App Frontend/src/Pages/Home/Home.css
- Web App Frontend/src/Pages/Home/Home.js
- Web App Frontend/src/Pages/MesAnnonces/MesAnnonces.js
- Web App Frontend/src/Pages/NewAnnonce/NewAnnonce.js
- Web App Frontend/src/Pages/Propositions/Propositions.js
Changements dans toutes les pages de la barre de navigation afin qu'elle soit unique et que le nom Annonces et Propositions soient modifiés partout
Changement dans CustomNavbar.js du nom du logo qui s'appelait React logo
Ajout des boutons dans la 3eme partie de l'écran de la page Home qui dirigent respectivement vers les pages propositions, annonces et, si on est pas connecté, login et register
> TT 161 et 162

- Web App Frontend/src/Components/UserCard/UserCard.js
- Web App Frontend/src/Pages/Register/Register.js
- backend/models/Users.js
- backend/routes/Propositions.js
- backend/routes/Users.js
Sauvegarde dans la DB du consentement de la personne.
Affichage de la bonne icone dans la page propositions
> TT 158 et 167

- Web App Frontend/src/Pages/Account/Account.css
- Web App Frontend/src/Pages/Account/Account.js
- Web App Frontend/src/Pages/Account/Account.test.js
- Web App Frontend/src/Pages/CreatePet/CreatePet.js
- backend/routes/Pets.js
- backend/routes/Users.js
Désormais lorsque l'on crée un nouvel annimal le local storage est mis à
jour pour le contenir. Si aucun animal n'était présent avant je remplace
l'attribut "Pets" par mon nouvel animal et si il existait déja une liste
d'animeaux, je push le mien dedans.
De plus, lors de la validation de l'animal nous ne sommes plus redirigé
vers l'accueil mais vers la page "account".
Désormais dans la page "Account" une image de + vient à la fin de toute
la liste des animeaux et permet de se rendre sur la page "CreatePet"
> TT#185 Liaison createAnimal à Account

- Web App Frontend/src/Pages/Account/Account.css
- Web App Frontend/src/Pages/Account/Account.js
- Web App Frontend/src/Pages/Account/Account.test.js
- Web App Frontend/src/Pages/DetailAnnonce/DetailAnnonce.js
- backend/models/Annonces.js
- backend/models/Pets.js
- backend/models/Propositions.js
- backend/models/Users.js
- backend/routes/Annonces.js
- backend/routes/Pets.js
- backend/routes/Propositions.js
- backend/routes/Users.js
- backend/test/Propositions.test.js
Le bouton dans la page Account va lancer une route pour anonymiser toutes les données sensibles
PS: je me suis battu avec sequelize pour faire cette magnifique route PUNAISE !!!
> Suppression profil#17

- backend/index.js
Ajout de la CORS Policy pour le déploiement 
Elle bloque toutes les requêtes qui ne viennent pas du frontend
> Ajout de la CORS Policy

- backend/routes/Users.js
> Hotfix Login

- Web App Frontend/src/Components/AddPetModal/AddPetModal.js
- Web App Frontend/src/Components/AddPetModal/AddPetModal.test.js
- Web App Frontend/src/Pages/DetailAnnonce/DetailAnnonce.js
- Web App Frontend/src/Pages/DetailAnnonce/DetailAnnonce.test.js
- Web App Frontend/src/Pages/NewAnnonce/NewAnnonce.css
- Web App Frontend/src/Pages/NewAnnonce/NewAnnonce.js
- backend/routes/Annonces.js
close #126 
close #145
Fix des Bugs cités plus haut.
Pas besoin de reset la DB normalement 
J'ai passé les TTs en urgent car on doit les avoir avant Jeudis :/
Merci
> TT #126 - TT #145

- netlify.toml
close #199
May god save the production 💯
> Hotfix Production build fix

- Web App Frontend/src/Components/AddSignalAnnonce/AddSignalAnnonce.js
- Web App Frontend/src/Components/AddSignalAnnonce/AddSignalAnnonce.test.js
- Web App Frontend/src/Components/AddSignalement/AddSignalement.js
- Web App Frontend/src/Components/AddSignalement/AddSignalement.test.js
- Web App Frontend/src/Components/Report/Report.js
- Web App Frontend/src/Components/Report/Report.test.js
- Web App Frontend/src/Pages/Admin/Admin.js
- Web App Frontend/src/Pages/DetailAnnonce/DetailAnnonce.css
- Web App Frontend/src/Pages/DetailAnnonce/DetailAnnonce.js
- Web App Frontend/src/Pages/DetailProposition/DetailProposition.js
- backend/routes/Admin.js
Ajout d'un bouton signalement dans la page detailAnnonce et la page detailProposition et envoi du signalement
Affichage dans la page admin des 2 signalements
> US 24 et 25

- .github/workflows/test-backend.yml
Skip Backend Testing 
=> Voir message Commit
> Backend Testing Skipping

- Web App Frontend/src/Pages/CreatePet/CreatePet.js
- Web App Frontend/src/Pages/CreatePet/CreatePet.test.js
Ajout de nouveau champ pour connaître la stérilité de l'animal, et sa tolérance envers les chiens , les chats et les enfants. Concernant la tolérence le formulaire enregistre Oui ou Non car il était impossible de renseigner un number ducoup une série de if change les oui par et 1 et les non par 0 avant l'envoit des informations.
> Amélioration formulaire "createAnimal"

- backend/routes/Users.js
Fix de dernier recourt juste avant la review
J'aime ma vie :-)
Voir message commit
> Hotfix Préreview 

- Web App Frontend/src/Pages/Login/Login.js
- Web App Frontend/src/Pages/Register/Register.js
- backend/routes/Users.js
Pour que le site de prod fonctionne
> Changement des clés capcha

- Web App Frontend/src/Components/UserCard/UserCard.js
- Web App Frontend/src/Components/UserCard/UserCard.test.js
- Web App Frontend/src/Pages/App/App.js
- Web App Frontend/src/Pages/MesPropositions/MesPropositions.js
- Web App Frontend/src/Pages/MesPropositions/MesPropositions.test.js
- Web App Frontend/src/Pages/Propositions/Propositions.js
- backend/routes/Propositions.js
jout de la page mes proposition ainsi que de la route associer
> US #174 page mes proposition 

- Web App Frontend/src/Pages/Account/Account.js
- backend/middleware/verifyToken.js
- backend/routes/Users.js
Voir message de commit 
Askip nathan m'a dit de faire ça:
Fine tunning du code de nathan car il a copié collé de stackoverflow et qu'il n'a pas essayé de comprendre ce qu'il a commit
Lorsque j'appelle les routes info, deleteUser et UpdateUser, le backend s'attend à recevoir le token
Il vérifie  alors que l'id de l'utilisateur trouvé dans le token et celui de la requête  sont cohérents
> Sécurisation de la route Users

- Web App Frontend/src/Components/NotificationCard/NotificationCard.js
Appel l'application mail avec le lien
> Ajout de la fonction mail

- Web App Frontend/src/Pages/CreateProposition/CreateProposition.js
- Web App Frontend/src/Pages/Register/Register.js
On enlève le fait de pouvoir mettre sa photo de profil car on a remplacé
cette fonctionnalité par un système d'avatar.
+
Réparation des bêtises de Kévin que j'ai autorisé
> Bug fix + suppression fonctionnalités

- backend/test/Pets.test.js
- backend/test/Users.test.js
Ajout de test pour la route Pets back end pour renforcer la sécuriter et l'integriter de la route
La route général pets , la route /pets/hasAnnonce et la route /pets/info on été tester dans le cas d'un bon fonctionnement et dans 2 cas ou elles ne sont pas sensé fonctionner
> Ajout de test Pets Back end
